kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ik-installer
subjects:
  - kind: ServiceAccount
    name: ik-installer
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: ik-installer
  apiGroup: rbac.authorization.k8s.io