{{- if .Values.Kubernetes -}}
apiVersion: logging.imaginekube.com/v1alpha2
kind: FluentBitConfig
metadata:
  name: fluent-bit-config
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  service:
    parsersFile: parsers.conf
  inputSelector:
    matchLabels:
      logging.imaginekube.com/enabled: "true"
  filterSelector:
    matchLabels:
      logging.imaginekube.com/enabled: "true"
  outputSelector:
    matchLabels:
      logging.imaginekube.com/enabled: "true"
  {{- end }}