# Default values for OpenELB.
# This is a YAML-formatted file.

admission:
  image:
    repository: imaginekubedev/kube-webhook-certgen
    tag: v1.1.1
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
    name: openelb-admission

manager:
  apiHosts: ":50051"
  webhookPort: 443
  image:
    repository: imaginekube/openelb
    tag: v0.5.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  terminationGracePeriodSeconds: 10
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  nodeSelector:
    kubernetes.io/os: linux
    #lb.imaginekube.com/v1alpha1: openelb
  serviceAccount:
    create: true
    name: openelb-manager
