apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/created-by: imaginekube.com/ik-apiserver
  labels:
    app: ik-apiserver
    tier: backend
    version: {{ .Chart.AppVersion }}
  name: ik-apiserver
  namespace: imaginekube-system
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
    {{- with .Values.apiserver.nodePort }}
      nodePort:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  selector:
    {{- if eq .Values.role "host" }}
    app: ik-apiserver
    {{- else }}
    app: ik-agent
    {{- end }}
    tier: backend
    # version: {{ .Chart.AppVersion }}
{{- if .Values.apiserver.nodePort }}
  type: NodePort
{{- else}}
  type: ClusterIP
{{- end}}
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ik-installer-manager
    tier: backend
    version: {{ .Chart.AppVersion }}
  name: ik-installer-manager
  namespace: imaginekube-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    {{- if eq .Values.role "host" }}
    app: ik-installer-manager
    {{- else }}
    app: ik-agent
    {{- end }}
    tier: backend
    # version: {{ .Chart.AppVersion }}
  sessionAffinity: None
  type: ClusterIP
